### ISSUE TITLE
Nothing happens when pressing enter

### ISSUE THREAD

**Issue by michaelmcmillan** [takac/vim-spotifysearch#10]
Hi there, this plugin looks awesome, but I can't get it to work properly. When I've searched for a song and "marked it" (by going to the line the song is on) nothing happens when I press enter.

I looked at the source (I'm a vim-noob) and noticed that the <CR> mapping executes <code>:silent call PlayTrackMapping()</code>. However, when I copy that exact command and try to run it manually (after selecting a song) nothing happens. I've also confirmed that running the <code>open *spotify-uri*</code> works from terminal. 

Do you have any advice on how I can get this working? :) Perhaps map it to a different key?

**Comment by takac** [comment]
Please let me know if this is still reproducible. Closing for now.
