### ISSUE TITLE
Can't play album list

### ISSUE THREAD

**Issue by taromero** [takac/vim-spotifysearch#17]
After selecting a song to play it plays correctly, but instead of continue playing the next song on the list that this plugin is showing, it continues playing from the last song I played on the Spotify GUI.

Is there a way to make it to continue playing the list that is displayed on this VIM plugin?

I'm using Ubuntu 14.04.

**Comment by takac** [comment]
This is a shortcoming of how the track is launched on Linux using "spotify <track-uri>" system call. On OSX you can use applescript to execute a song play in context of an album. If you can work out a way of doing this with a plain system call then it can be done. Sorry took so long to get back.
