### ISSUE TITLE
Errors When Selecting a Song

### ISSUE THREAD

**Issue by ijcuevas2** [takac/vim-spotifysearch#19]
I can do a spotify search but when I select a song I get this error:

Error detected while processing function FollowMapping..TrackFollow..LinuxUriOpener..<SNR>25_SystemCallWrapper:
line    3:
E605: Exception not caught: Non zero exit code [127] from: spotify spotify:track:6GIQckKtzHYA8MHoRWRkcy
Error detected while processing function FollowMapping..TrackFollow:
line   11:
E171: Missing :endif

 I also get this error when I ssh into my school's servers using putty. I get a similar error on Windows 10 in gvim, where instead of "LinuxUriOpener" it says "WindowsUriOpener".

Both use Vim 7.4.

**Comment by takac** [comment]
Error code 127 indicates that the command "spotify" wasn't found. i.e. It is not installed or not on your $PATH.

**Comment by ijcuevas2** [comment]
So I installed spotify on my Windows 10 laptop, but when I do :Spotify <song>, I receive the same errors and spotify will open instead.

**Comment by takac** [comment]
Haven't tested on Windows 10. The links are launched through explorer. Try
to open a Spotify uri with cmd and the uri, e.g. 'explorer
spotify:track:0QQ72UmBybbZDVb2jXEO0c'

**Comment by ijcuevas2** [comment]
So on windows 10 when I run that on cmd, then I get a notification "You'll need a new app to open this spotify" ("Look for app in store" and a checkbox with "always use this app"). This issue in Windows 10 is not so relevant to me.

Btw, I don't know if this better, but now when I select a song in the Linux OS, the only error I get is 

E117: Unknown Function: FollowMapping
