### ISSUE TITLE
ImportError: No module named spotipy

### ISSUE THREAD

**Issue by MateuszBelczowski** [takac/vim-spotifysearch#27]
I can't get your plugin working. I've installed it and when I try to search for a track with vim command `:Spotify track_name` I get an error 

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named spotipy

I can't figure out which python is being used, because I've installed spotipy for python2 and python3 globally and this import works fine in python console for both versions

>  Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> &gt;>> import spotipy
> &gt;>> 

> Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> &gt;>> import spotipy
> &gt;>>

My vim version is 7.4. Could you tell me what I'm missing?

**Comment by takac** [comment]
Is this happening in the Vim GUI or on the terminal version of Vim? I've had similar issues in the past where the GUI version (in my case MacVim) was linking to another python.

**Comment by MateuszBelczowski** [comment]
I'm using the terminal version of vim on Ubuntu 16.04. Could you tell me how can I check which version of python is being invoked?

**Comment by takac** [comment]
`vim --version` should display some details about where it is linking to python.

**Comment by MateuszBelczowski** [comment]
Thanks, I got it working! I had something messed up with my global python interpreters ;) Cheers!
